openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: lueilwitz.sofia@example.org
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: omnis
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/password/reset:
    post:
      summary: ''
      operationId: postApiPasswordReset
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: sapiente
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: shemar.abernathy@example.org
                  nullable: false
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: '@k~gG"{Z+'
                  nullable: false
              required:
                - token
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: ''
      operationId: postApiLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/devices:
    get:
      summary: ''
      operationId: getApiDevices
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiDevices
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                device_code:
                  type: string
                  description: ''
                  example: quis
                  nullable: false
                name:
                  type: string
                  description: ''
                  example: natus
                  nullable: false
                location:
                  type: string
                  description: ''
                  example: quis
                  nullable: true
                device_type:
                  type: string
                  description: ''
                  example: voluptatem
                  nullable: false
              required:
                - device_code
                - name
                - device_type
      security: []
  '/api/devices/{id}':
    get:
      summary: ''
      operationId: getApiDevicesId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiDevicesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: omnis
                  nullable: false
                location:
                  type: string
                  description: ''
                  example: in
                  nullable: true
                device_type:
                  type: string
                  description: ''
                  example: sed
                  nullable: false
                is_claimed:
                  type: boolean
                  description: ''
                  example: false
                  nullable: false
              required:
                - name
                - device_type
      security: []
    delete:
      summary: ''
      operationId: deleteApiDevicesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the device.'
        example: 18
        required: true
        schema:
          type: integer
  '/api/devices/{device_id}/settings':
    get:
      summary: ''
      operationId: getApiDevicesDevice_idSettings
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiDevicesDevice_idSettings
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                lamp_mode:
                  type: string
                  description: ''
                  example: repudiandae
                  nullable: true
                water_min_level:
                  type: integer
                  description: ''
                  example: 6
                  nullable: true
                water_max_level:
                  type: integer
                  description: ''
                  example: 6
                  nullable: true
                tank_height_cm:
                  type: integer
                  description: ''
                  example: 6
                  nullable: true
      security: []
    parameters:
      -
        in: path
        name: device_id
        description: 'The ID of the device.'
        example: 14
        required: true
        schema:
          type: integer
  '/api/devices/{device_id}/alerts':
    get:
      summary: ''
      operationId: getApiDevicesDevice_idAlerts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiDevicesDevice_idAlerts
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: ''
                  example: dicta
                  nullable: false
                message:
                  type: string
                  description: ''
                  example: sit
                  nullable: false
              required:
                - type
                - message
      security: []
    parameters:
      -
        in: path
        name: device_id
        description: 'The ID of the device.'
        example: 14
        required: true
        schema:
          type: integer
  '/api/alerts/{alert_id}/read':
    put:
      summary: ''
      operationId: putApiAlertsAlert_idRead
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: alert_id
        description: 'The ID of the alert.'
        example: 13
        required: true
        schema:
          type: integer
  '/api/reset-password/{token}':
    get:
      summary: ''
      operationId: getApiResetPasswordToken
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: ''
                properties:
                  message:
                    type: string
                    example: ''
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: token
        description: ''
        example: voluptas
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
